name: "[Deploy] Nginx Upgrade the release"

on:
  workflow_dispatch:

  # push:
  #   branches: [ main ]

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read

    uses: ./.github/workflows/3-2_deploy-canary-gke.yml
    with:
      namespace: nginx
      zone: asia-northeast3-a
    secrets:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      GKE_PROVIDER_ID: ${{ secrets.GKE_PROVIDER_ID }}
      GKE_SERVICE_ACCOUNT: ${{ secrets.GKE_SERVICE_ACCOUNT }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
